apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: y6zniuibk-java-springboot
  janus-idp.io/tekton: y6zniuibk-java-springboot
  backstage.io/kubernetes-id: y6zniuibk-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: y6zniuibk-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
